import News from "../component/News"
import PageHero from "../component/PageHero";
import NewsHero from '../public/img/news-hero.jpeg';
import { Container, Row, Col } from "react-bootstrap";

const news = () => {
    return(
        <main>
            <PageHero text="News" image={NewsHero} />
            <section>
                <Container>
                    <Row className="justify-content-center">
                        <Col md={7}>
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                            <News title="A Story That Stands Like a Dam" description='The University of Utah Press has published a new edition of Russell Martin&apos;s highly renowned nonfiction book A Story That Stands Like A Dam, winner of the Caroline Bancroft History Prize. Outside Magazine writes,&quot; The story of Glen Canyon is also a tale of lost innocence. Martin&apos;s book tells it wonderfully.&quot; The Los Angeles Times adds, &quot;Read Martin&apos;s fine book. We have needed such a record of the war between our appetites and our dreams, and now we&apos;ve got it.&quot;' link='Buy it at Amazon' url='https://www.amazon.com/Story-that-Stands-Like-Dam/dp/1607815672/ref=asap_bc?ie=UTF8' />
                        </Col>
                    </Row>
                </Container>
            </section>
        </main>
    )
}

export default news;